constructor {
  Create : ();
};

service Onlyhack {
  /// #[payable]
  /// #[returns_value]
  BuyContent : (model_id: actor_id, content_id: u64, pk_bytes: str) -> vec u8;
  ModelAddPaidContent : (paid_content: struct { str, str, u128 }) -> u64;
  ModelCreateProfile : (name: str, about: str, open_content: vec str) -> null;
  query GetEncContent : (model_id: actor_id, content_id: u64) -> vec u8;
  query GetProfile : (model_id: actor_id) -> struct { str, str, vec struct { u64, str }, vec struct { u64, struct { str, str, u128 } } };
  query GetProfiles : () -> vec struct { str, str, vec struct { u64, str }, vec struct { u64, str, u128, vec u8, vec u8 }, vec struct { u64, str, u128 } };
};

