// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct OnlyhackClientProgram;
impl sails_rs::client::Program for OnlyhackClientProgram {}
pub trait OnlyhackClient {
    type Env: sails_rs::client::GearEnv;
    fn onlyhack(&self) -> sails_rs::client::Service<onlyhack::OnlyhackImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OnlyhackClient
    for sails_rs::client::Actor<OnlyhackClientProgram, E>
{
    type Env = E;
    fn onlyhack(&self) -> sails_rs::client::Service<onlyhack::OnlyhackImpl, Self::Env> {
        self.service(stringify!(Onlyhack))
    }
}
pub trait OnlyhackClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self) -> sails_rs::client::PendingCtor<OnlyhackClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OnlyhackClientCtors
    for sails_rs::client::Deployment<OnlyhackClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<OnlyhackClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod onlyhack {
    use super::*;
    pub trait Onlyhack {
        type Env: sails_rs::client::GearEnv;
        /// #[payable]
        /// #[returns_value]
        fn buy_content(
            &mut self,
            model_id: ActorId,
            content_id: u64,
            pk_bytes: String,
        ) -> sails_rs::client::PendingCall<io::BuyContent, Self::Env>;
        fn model_add_paid_content(
            &mut self,
            paid_content: (String, String, u128),
        ) -> sails_rs::client::PendingCall<io::ModelAddPaidContent, Self::Env>;
        fn model_create_profile(
            &mut self,
            name: String,
            about: String,
            open_content: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::ModelCreateProfile, Self::Env>;
        fn get_enc_content(
            &self,
            model_id: ActorId,
            content_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetEncContent, Self::Env>;
        fn get_profile(
            &self,
            model_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProfile, Self::Env>;
    }
    pub struct OnlyhackImpl;
    impl<E: sails_rs::client::GearEnv> Onlyhack for sails_rs::client::Service<OnlyhackImpl, E> {
        type Env = E;
        fn buy_content(
            &mut self,
            model_id: ActorId,
            content_id: u64,
            pk_bytes: String,
        ) -> sails_rs::client::PendingCall<io::BuyContent, Self::Env> {
            self.pending_call((model_id, content_id, pk_bytes))
        }
        fn model_add_paid_content(
            &mut self,
            paid_content: (String, String, u128),
        ) -> sails_rs::client::PendingCall<io::ModelAddPaidContent, Self::Env> {
            self.pending_call((paid_content,))
        }
        fn model_create_profile(
            &mut self,
            name: String,
            about: String,
            open_content: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::ModelCreateProfile, Self::Env> {
            self.pending_call((name, about, open_content))
        }
        fn get_enc_content(
            &self,
            model_id: ActorId,
            content_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetEncContent, Self::Env> {
            self.pending_call((model_id, content_id))
        }
        fn get_profile(
            &self,
            model_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProfile, Self::Env> {
            self.pending_call((model_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(BuyContent (model_id: ActorId, content_id: u64, pk_bytes: String) -> Vec<u8>);
        sails_rs::io_struct_impl!(ModelAddPaidContent (paid_content: (String,String,u128,)) -> u64);
        sails_rs::io_struct_impl!(ModelCreateProfile (name: String, about: String, open_content: Vec<String>) -> ());
        sails_rs::io_struct_impl!(GetEncContent (model_id: ActorId, content_id: u64) -> Vec<u8>);
        sails_rs::io_struct_impl!(GetProfile (model_id: ActorId) -> (String,String,Vec<(u64,String,)>,Vec<(u64,(String,String,u128,),)>,));
    }
}
