[package]
name = "onlyhack-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Package containing business logic for the program"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs.workspace = true
parity-scale-codec = { version = "3.7.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }
dleq-secret = { git = "https://github.com/grishasobol/dleq-secret", default-features = false }
hex = { version = "0.4.3", default-features = false }
